# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "mpt3sas" "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c7f9b615-5e1c-4015-8824-b17fbce9b7cc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c7f9b615-5e1c-4015-8824-b17fbce9b7cc".device = "/dev/disk/by-uuid/c7f9b615-5e1c-4015-8824-b17fbce9b7cc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F08D-5007";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-18ebd863-bc36-473e-a37b-1574c9357791"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
