{ config, pkgs, configName, ... }:
let

  firefox-custom = pkgs.wrapFirefox pkgs.firefox-unwrapped {
    extraPolicies = {
      CaptivePortal = false;
      DisableFirefoxStudies = true;
      DisablePocket = true;
      DisableTelemetry = true;
      DisableFirefoxAccounts = true;
      DisableProfileImport = true;
      DisableProfileRefresh = true;
      DisableSystemAddonUpdate = true;

      FirefoxHome = {
        Pocket = false;
        Snippets = false;
      };

      UserMessaging = {
        ExtensionRecommendations = false;
        SkipOnboarding = true;
      };

      Extensions.Install = [
        "https://addons.mozilla.org/firefox/downloads/file/3933192/ublock_origin-1.42.4.xpi"
        "https://addons.mozilla.org/firefox/downloads/file/3948477/i_dont_care_about_cookies-3.4.0.xpi"
        "https://addons.mozilla.org/firefox/downloads/file/3941589/return_youtube_dislikes-3.0.0.1.xpi"
        "https://addons.mozilla.org/firefox/downloads/file/3958238/sponsorblock-4.5.1.xpi"
        "https://addons.mozilla.org/firefox/downloads/file/3059971/image_search_options-3.0.12.xpi"
        "https://cdn.frankerfacez.com/script/frankerfacez-4.0-an+fx.xpi"
        "https://addons.mozilla.org/firefox/downloads/file/3945159/7tv-2.2.2.xpi"
      ];
    };

    extraPrefs = ''
      // show more ssl cert infos
      lockPref("security.identityblock.show_extended_validation", true);

      // DDG is fucked so might as well use a better botnet
      lockPref("browser.policies.runOncePerModification.setDefaultSearchEngine", "Google");

      lockPref("privacy.sanitize.sanitizeOnShutdown", false); // don't clear cookies/history
      lockPref("browser.startup.page", 3); // restore tabs on startup

      //this seems to cause bugs when i click links on a fullscreened firefox
      //lockPref("browser.link.open_newwindow", 2); // open links in new windows (for exwm)

      // fuck off with this sponsored shit
      lockPref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsored", false);
      lockPref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSites", false);
    '';
  };

in with config; {

  imports = [../home.nix ];

  home.packages = with pkgs; [
    font-awesome
    fira-mono
    roboto

    v4l-utils
    gh2md
    gist
    autorandr # save and detect xrandr configurations automatically
    fusee-launcher
    pass

    pinentry-gnome
    gcr # required for pinentry-gnome?
    polkit_gnome
    gnome3.nautilus

    dmenu
    tdesktop
    chatterino7
    obs-studio
    simplescreenrecorder
    screenkey
    pavucontrol
    krita

    (pkgs.buildEnv { name = "scripts-${configName}"; paths = [ ./scripts ]; })
  ];

  xsession = {
    enable = true;
    windowManager.command = ''
      exec emacs --debug-init -mm
    '';
  };

  xsession.scriptPath = ".hm-xsession";

  xdg.configFile = {
    "emacs/machine-specific.el".source = ./emacs/init.el;

    # extra elisp that needs to include strings generated by nix
    "emacs/machine-specific-generated.el".text = ''
      (setq loli/polkit-agent-command "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1")
      (setq loli/browser-command "${firefox-custom}/bin/firefox")
      (setq loli/chatterino-command "${pkgs.chatterino7}/bin/chatterino")
      (setq loli/telegram-command "${pkgs.tdesktop}/bin/telegram-desktop")

      (defun loli/passmenu ()
        "run password manager menu"
        (interactive)
        (loli/shell "${pkgs.pass}/bin/passmenu"))

      (defun loli/screenshot-to-clipboard ()
        "select a section to screenshot and copy png to clipboard"
        (interactive)
        (loli/shell "${pkgs.maim}/bin/maim -s --format png /dev/stdout |
                     ${pkgs.xclip}/bin/xclip -selection clipboard -t image/png -i"))

      (defun loli/exwm-randr-screen-change ()
        "runs when the exwm screen changes. for example, when you plug/unplug a monitor"
        (loli/shell "${pkgs.autorandr}/bin/autorandr --change --force")
        (message "autorandr config: %s"
                (string-trim (shell-command-to-string "${pkgs.autorandr}/bin/autorandr --current"))))
    '';
  };

  services.barrier.client = {
    enable = true;
    server = "192.168.1.202";
    enableDragDrop = true;
  };

  services.blueman-applet.enable = true;

  services.polybar = {
    enable = true;
    package = pkgs.polybar.override {
      pulseSupport = true;
    };
    script = ''
      polybar top --reload &
    '';
  };

  services.polybar.config = {

    colors = {
      underline-1 = "#c792ea";
      foreground-alt = "#555";
      secondary = "#e60053";
    };

    "bar/top" = {
      #monitor = "HDMI-A-0";
      width = "100%";
      height = "32px";
      radius = 0;
      modules-center = "date";
      modules-left = "cpu temperature memory";
      modules-right = "filesystem volume";
      padding-right = 2;
      padding-left = 2;
      separator = "   ";
      tray-position = "right"; # enables tray on right side (disabled otherwise)
      cursor-click = "pointer"; # instead of the X
      cursor-scroll = "ns-resize"; # instead of the X
      tray-maxsize = 28;
      line-size = 2;
      line-color = "#f00";

      #font-0 = "Noto Sans:weight=bold";
      font-0 = "Noto Sans:weight=bold";
      font-1 = "Font Awesome";
      font-2 = "Material Icons";
      font-3 = "Fira Mono:size=8";
      # some emoji fonts need scale= otherwise they appear way too big
      #font-4 = "Noto Emoji:scale=6";
    };

    "module/volume" = {
      # the polybar module is supposed to convert things like format.volume -> format-volume.
      # this doesn't seem to work, so I have to name them like the actual polybar cfg.
      # array conversion also doesn't seem to work.
      # also, for some reason format-underline doesn't work for this volume module
      type = "internal/pulseaudio";
      format-volume = "<ramp-volume> <label-volume>";
      label-muted = "";
      label-muted-foreground = "#ff7777";
      ramp-volume-0 = "";
      ramp-volume-1 = "";
      ramp-volume-2 = "";
      ramp-volume-3 = "";
      click-right = "pavucontrol";
    };

    "module/date" = {
      type = "internal/date";
      internal = 5;
      date-alt = "%Y-%m-%d";
      time-alt = "%H:%M:%S";
      date = "%A, %d %B %Y";
      time = "%H:%M";
      label = "%date% %time%";
      format = " <label>";
      format-underline = "\${colors.underline-1}";
    };

    "module/cpu" = {
      type = "internal/cpu";
      interval = 2;
      format = "<label> <ramp-coreload>";
      format-underline = "\${colors.underline-1}";
      click-left = ''
        emacsclient -e "(proced)"
      '';
      label = "%percentage:2%%";
      ramp-coreload-spacing = 0;
      ramp-coreload-0-foreground = "\${colors.foreground-alt}";
      ramp-coreload-0 = "▁";
      ramp-coreload-1 = "▂";
      ramp-coreload-2 = "▃";
      ramp-coreload-3 = "▄";
      ramp-coreload-4 = "▅";
      ramp-coreload-5 = "▆";
      ramp-coreload-6 = "▇";
    };

    "module/memory" = {
      type = "internal/memory";
      interval = 3;
      warn-percentage = 95;
      format = "<ramp-used> <label>";
      label = " %gb_used%/%gb_total%";
      ramp-used-0 = "▁";
      ramp-used-1 = "▂";
      ramp-used-2 = "▃";
      ramp-used-3 = "▄";
      ramp-used-4 = "▅";
      ramp-used-5 = "▆";
      ramp-used-6 = "▇";
      format-underline = "\${colors.underline-1}";
    };

    "module/temperature" = {
      type = "internal/temperature";
      thermal-zone = 0;
      warn-temperature = 60;

      format = "<label>";
      format-underline = "\${colors.underline-1}";
      format-warn = "<label-warn>";
      format-warn-underline = "\${self.format-underline}";

      label = "%temperature-c%";
      label-warn = "%temperature-c%!";
      label-warn-foreground = "\${colors.secondary}";
    };

    "module/filesystem" = {
      type = "internal/fs";
      mount-0 = "/home";
      interval = 10;
      fixed-values = true;
      spacing = 4;
      warn-percentage = 75;
      label-mounted = " %mountpoint% %percentage_used%%";
      format-underline = "\${colors.underline-1}";
    };

  };

  services.parcellite = {
    enable = true;
    package = pkgs.clipit;
  };

  xresources.properties = {
    "*xterm*faceName" = "PxPlus IBM VGA8";
    "*xterm*faceNameDoublesize" = "Unifont";
    "*xterm*faceSize" = 12;
    "*xterm*allowBoldFonts" =  false;
    "*xterm*background" = "black";
    "*xterm*foreground" = "grey";
    "*xterm*reverseVideo" = false;
    "*xterm*termName" = "xterm-256color";
    "*xterm*VT100.Translations" = ''#override \
      Shift <Key>Insert: insert-selection(CLIPBOARD) \n\
      Ctrl Shift <Key>V: insert-selection(CLIPBOARD) \n\
      Ctrl Shift <Key>C: copy-selection(CLIPBOARD)
    '';
  };

  programs.gpg = {
    enable = true;
    homedir = "${xdg.dataHome}/gnupg";
    settings.use-agent = true;
  };

  home.file."${programs.gpg.homedir}/.keep".text = "";

  services.gpg-agent = {
    enable = true;
    defaultCacheTtl = 31536000;
    maxCacheTtl = 31536000;
    pinentryFlavor = "gnome3";
  };

  services.gnome-keyring.enable = true;

  xdg.mimeApps.defaultApplications = {
    "x-scheme-handler/http" = "firefox.desktop";
    "x-scheme-handler/https" = "firefox.desktop";
    "text/html" = "firefox.desktop";
    "application/x-extension-htm" = "firefox.desktop";
    "application/x-extension-html" = "firefox.desktop";
    "application/x-extension-shtml" = "firefox.desktop";
    "application/xhtml+xml" = "firefox.desktop";
    "application/x-extension-xhtml" = "firefox.desktop";
    "application/x-extension-xht" = "firefox.desktop";
  };

  home.sessionVariables.DEFAULT_BROWSER = "${firefox-custom}/bin/firefox";

  # NOTE: private config files. comment out or provide your own
  xdg.configFile."gh2md/token".source = ../secrets/gh2md/token;
  home.file.".gist".source = ../secrets/gist/token;

}
